apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tragic-reptile-nodejs 
  janus-idp.io/tekton: tragic-reptile-nodejs
  backstage.io/kubernetes-id: tragic-reptile-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tragic-reptile-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  