apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tragic-reptile-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tragic-reptile-nodejs 
  name: tragic-reptile-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: tragic-reptile-nodejs 
